try{
  console.log(a);
}
catch{
  console.log("caught an eror")
}